### ISSUE TITLE
请问如何使用这个机器人

### ISSUE THREAD

**Issue by albertyou2** [liangjz92/deeplearning4chatbot#1]
@liangjz92 
请问如何使用这个机器人？

**Comment by liangjz92** [comment]
不是一个具体的机器人，只是一些自己实现的可以用于对话机器人的深度模型
具体使用需要找一些聊天记录当做语料

**Comment by albertyou2** [comment]
@liangjz92 谢谢回复
我明白。我的想法就假如我有一些聊天记录的预料库。如何训练以及使用您的代码呢？
是否有有一个简单地使用说明之类的。非常感谢！

**Comment by liangjz92** [comment]
@albertyou2 ，ok，最近在忙其他事情，过几天会继续完善代码和文档，到时候@ 你

**Comment by albertyou2** [comment]
@liangjz92 太感谢了！
